name: CI|CD

on:
  push:
    tags:
      - v*

jobs:
  flutter_test:
    permissions:
      id-token: write
      contents: read
      checks: write
    name: Run flutter analyze and flutter_test
    #runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --output=none --set-exit-if-changed lib/
      - run: dart format --output=none --set-exit-if-changed test/
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 15
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build appbundle
      #- run: flutter build appbundle
      - run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*, build/app/outputs/bundle/release/*, build/ios/iphoneos/app.ipa"
          #artifacts: "build/app/outputs/bundle/release/*"
          tag: v1.0.${{ github.run_number }}
          #token: ${{ secrets.GITHUB_TOKEN }}
